id: P006625
initial_creation_type: ocr
created_at: 21/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W1KG16672
  title: རྒྱལ་རོང་དམངས་ཁྲོད་ཀྱི་རྩིས་ཡིག་ཕྱོགས་བསྒྲིགས།
  author: ''
  volumes:
    948f7516b49e40deb3f2ec78ed8267cb:
      image_group_id: I4PD3932
      title: ''
      volume_number: 1
      total_pages: 362
      base_file: v001.txt
